export enum KeywordCategory {
    DAMAGE_TYPE = "DAMAGE_TYPE",
    CARD_STAT = "CARD_STAT",
    EXTENSION = "EXTENSION",
    EFFECT_ID = "EFFECT_ID",
    EFFECT_MODIFIER = "EFFECT_MODIFIER",
    PLAYER_STAT = "PLAYER_STAT",
    EFFECT_TYPE = "EFFECT_TYPE",
    EFFECT_SUBTYPE = "EFFECT_SUBTYPE"
}